# adapted from https://github.com/JuliaCN/JuliaZH.jl/blob/master/contrib/Dockerfile
FROM juliadocs/documenter-latex:0.1
RUN apt-get update && \
    apt-get install -y \
    texlive-full \
    texlive-xetex \
    texlive-lang-chinese